/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as InteractionsRouteImport } from './routes/interactions'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrescriptionReviewRouteImport } from './routes/prescription.review'
import { Route as PrescriptionNewRouteImport } from './routes/prescription.new'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as PrescriptionRxIdOrdonnanceRouteImport } from './routes/prescription.$rxId.ordonnance'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsRoute = InteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionReviewRoute = PrescriptionReviewRouteImport.update({
  id: '/prescription/review',
  path: '/prescription/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionNewRoute = PrescriptionNewRouteImport.update({
  id: '/prescription/new',
  path: '/prescription/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)
const PrescriptionRxIdOrdonnanceRoute =
  PrescriptionRxIdOrdonnanceRouteImport.update({
    id: '/prescription/$rxId/ordonnance',
    path: '/prescription/$rxId/ordonnance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/interactions': typeof InteractionsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/prescription/new': typeof PrescriptionNewRoute
  '/prescription/review': typeof PrescriptionReviewRoute
  '/prescription/$rxId/ordonnance': typeof PrescriptionRxIdOrdonnanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/interactions': typeof InteractionsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/prescription/new': typeof PrescriptionNewRoute
  '/prescription/review': typeof PrescriptionReviewRoute
  '/prescription/$rxId/ordonnance': typeof PrescriptionRxIdOrdonnanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/interactions': typeof InteractionsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/prescription/new': typeof PrescriptionNewRoute
  '/prescription/review': typeof PrescriptionReviewRoute
  '/prescription/$rxId/ordonnance': typeof PrescriptionRxIdOrdonnanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/interactions'
    | '/patients'
    | '/settings'
    | '/patients/$patientId'
    | '/prescription/new'
    | '/prescription/review'
    | '/prescription/$rxId/ordonnance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/interactions'
    | '/patients'
    | '/settings'
    | '/patients/$patientId'
    | '/prescription/new'
    | '/prescription/review'
    | '/prescription/$rxId/ordonnance'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/interactions'
    | '/patients'
    | '/settings'
    | '/patients/$patientId'
    | '/prescription/new'
    | '/prescription/review'
    | '/prescription/$rxId/ordonnance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  InteractionsRoute: typeof InteractionsRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  PrescriptionNewRoute: typeof PrescriptionNewRoute
  PrescriptionReviewRoute: typeof PrescriptionReviewRoute
  PrescriptionRxIdOrdonnanceRoute: typeof PrescriptionRxIdOrdonnanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions': {
      id: '/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof InteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription/review': {
      id: '/prescription/review'
      path: '/prescription/review'
      fullPath: '/prescription/review'
      preLoaderRoute: typeof PrescriptionReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription/new': {
      id: '/prescription/new'
      path: '/prescription/new'
      fullPath: '/prescription/new'
      preLoaderRoute: typeof PrescriptionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/prescription/$rxId/ordonnance': {
      id: '/prescription/$rxId/ordonnance'
      path: '/prescription/$rxId/ordonnance'
      fullPath: '/prescription/$rxId/ordonnance'
      preLoaderRoute: typeof PrescriptionRxIdOrdonnanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  InteractionsRoute: InteractionsRoute,
  PatientsRoute: PatientsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  PrescriptionNewRoute: PrescriptionNewRoute,
  PrescriptionReviewRoute: PrescriptionReviewRoute,
  PrescriptionRxIdOrdonnanceRoute: PrescriptionRxIdOrdonnanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
