/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge-graph'
import { Route as InteractionsRouteImport } from './routes/interactions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrescriptionReviewRouteImport } from './routes/prescription.review'
import { Route as PrescriptionNewRouteImport } from './routes/prescription.new'

const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsRoute = InteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionReviewRoute = PrescriptionReviewRouteImport.update({
  id: '/prescription/review',
  path: '/prescription/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionNewRoute = PrescriptionNewRouteImport.update({
  id: '/prescription/new',
  path: '/prescription/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interactions': typeof InteractionsRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/patients': typeof PatientsRoute
  '/prescription/new': typeof PrescriptionNewRoute
  '/prescription/review': typeof PrescriptionReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interactions': typeof InteractionsRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/patients': typeof PatientsRoute
  '/prescription/new': typeof PrescriptionNewRoute
  '/prescription/review': typeof PrescriptionReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interactions': typeof InteractionsRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/patients': typeof PatientsRoute
  '/prescription/new': typeof PrescriptionNewRoute
  '/prescription/review': typeof PrescriptionReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interactions'
    | '/knowledge-graph'
    | '/patients'
    | '/prescription/new'
    | '/prescription/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/interactions'
    | '/knowledge-graph'
    | '/patients'
    | '/prescription/new'
    | '/prescription/review'
  id:
    | '__root__'
    | '/'
    | '/interactions'
    | '/knowledge-graph'
    | '/patients'
    | '/prescription/new'
    | '/prescription/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InteractionsRoute: typeof InteractionsRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  PatientsRoute: typeof PatientsRoute
  PrescriptionNewRoute: typeof PrescriptionNewRoute
  PrescriptionReviewRoute: typeof PrescriptionReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions': {
      id: '/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof InteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription/review': {
      id: '/prescription/review'
      path: '/prescription/review'
      fullPath: '/prescription/review'
      preLoaderRoute: typeof PrescriptionReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription/new': {
      id: '/prescription/new'
      path: '/prescription/new'
      fullPath: '/prescription/new'
      preLoaderRoute: typeof PrescriptionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InteractionsRoute: InteractionsRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  PatientsRoute: PatientsRoute,
  PrescriptionNewRoute: PrescriptionNewRoute,
  PrescriptionReviewRoute: PrescriptionReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
